# Configuration file for Antibody Training Pipeline with ESM embeddings

# Model configuration
model:
  name: "facebook/esm1v_t33_650M_UR90S_1"  # ESM-1V model from HuggingFace
  device: "mps"  # [cuda, cpu, mps] - temporarily using CPU due to torch version

# Data configuration
data:
  train_file: ./train_datasets/VH_only_training_ready.csv  # Path to training data (sequences and labels)
  val_file: null    # Path to validation data (optional)
  test_file: null   # Path to test data (optional)
  
  # Data format options
  sequence_column: "sequence"  # Column name for protein sequences
  label_column: "label"       # Column name for binary labels
  
  # Data preprocessing
  max_sequence_length: 1024   # Maximum sequence length for ESM tokenizer
  
  # Data storage
  save_embeddings: true       # Whether to save computed embeddings
  embeddings_cache_dir: "./embeddings_cache"  # Directory to cache embeddings

# Classifier configuration
classifier:
  type: "logistic_regression"
  max_iter: 1000              # Maximum iterations for logistic regression
  random_state: 42            # Random seed for reproducibility
  class_weight: "None"    # Class weight for logistic regression

  # Cross-validation settings (performed on training data only)
  cv_folds: 10                # Number of folds for cross-validation on training data
  stratify: false              # Whether to use stratified CV

# Training configuration
training:
  # Evaluation metrics
  metrics: ["accuracy", "precision", "recall", "f1", "roc_auc"]
  
  # Model saving
  save_model: true
  model_name: "vh_classifier_BATCHED"  # Name for the saved model (without extension)
  model_save_dir: "./models"  # Directory to save models
  
  # Logging
  log_level: "INFO"           # Logging level: DEBUG, INFO, WARNING, ERROR
  log_file: "./logs/training.log"  # Log file path
  
  # Performance optimization
  batch_size: 8              # Batch size for embedding extraction
  num_workers: 4              # Number of workers for data loading

# Experiment tracking (optional)
experiment:
  name: "vh_only"
  description: "Binary classification of antibody sequences using ESM-1V embeddings"
  tags: ["antibody", "esm", "classification"]
  
# Hardware configuration
hardware:
  gpu_memory_fraction: 0.8    # Fraction of GPU memory to use
  clear_cache_frequency: 100  # Clear GPU cache every N sequences
